# parent image
FROM alpine

# Copy python requirements file
COPY requirements.txt /tmp/requirements.txt

# OS installs, pip installs, etc.
RUN apk add --no-cache \
    python3 \
    bash && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    pip3 install -r /tmp/requirements.txt

# copy app dir
COPY ./app /app
WORKDIR /app

# set environment vars
ENV FLASK_APP=main.py
ENV FLASK_DEBUG=1

CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]
